name: Trigger auto deployment for class-compass-server-mini-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/class-compass-server-mini-app-AutoDeployTrigger-fa2c5b41-2628-49f8-a961-17356c209f7e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLASSCOMPASSSERVERMINIAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CLASSCOMPASSSERVERMINIAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CLASSCOMPASSSERVERMINIAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.CLASSCOMPASSSERVERMINIAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLASSCOMPASSSERVERMINIAPP_REGISTRY_PASSWORD }}
          containerAppName: class-compass-server-mini-app
          resourceGroup: class-compass-server-mini-rg
          imageToBuild: ghcr.io/class-compass-server-mini-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


